#pragma once

#include <stdint.h>
#include "SDL3/SDL_keycode.h"

typedef uint32_t FE_Keycode;

//#define FEK_EXTENDED_MASK          (1u << 29)
//#define FEK_SCANCODE_MASK          (1u << 30)
//#define FE_SCANCODE_TO_KEYCODE(X)  (X | FEK_SCANCODE_MASK)

constexpr FE_Keycode FEK_UNKNOWN                 = 0x00000000u; /**< 0 */
constexpr FE_Keycode FEK_RETURN                  = 0x0000000du; /**< '\r' */
constexpr FE_Keycode FEK_ESCAPE                  = 0x0000001bu; /**< '\x1B' */
constexpr FE_Keycode FEK_BACKSPACE               = 0x00000008u; /**< '\b' */
constexpr FE_Keycode FEK_TAB                     = 0x00000009u; /**< '\t' */
constexpr FE_Keycode FEK_SPACE                   = 0x00000020u; /**< ' ' */
constexpr FE_Keycode FEK_EXCLAIM                 = 0x00000021u; /**< '!' */
constexpr FE_Keycode FEK_DBLAPOSTROPHE           = 0x00000022u; /**< '"' */
constexpr FE_Keycode FEK_HASH                    = 0x00000023u; /**< '#' */
constexpr FE_Keycode FEK_DOLLAR                  = 0x00000024u; /**< '$' */
constexpr FE_Keycode FEK_PERCENT                 = 0x00000025u; /**< '%' */
constexpr FE_Keycode FEK_AMPERSAND               = 0x00000026u; /**< '&' */
constexpr FE_Keycode FEK_APOSTROPHE              = 0x00000027u; /**< '\'' */
constexpr FE_Keycode FEK_LEFTPAREN               = 0x00000028u; /**< '(' */
constexpr FE_Keycode FEK_RIGHTPAREN              = 0x00000029u; /**< ')' */
constexpr FE_Keycode FEK_ASTERISK                = 0x0000002au; /**< '*' */
constexpr FE_Keycode FEK_PLUS                    = 0x0000002bu; /**< '+' */
constexpr FE_Keycode FEK_COMMA                   = 0x0000002cu; /**< ',' */
constexpr FE_Keycode FEK_MINUS                   = 0x0000002du; /**< '-' */
constexpr FE_Keycode FEK_PERIOD                  = 0x0000002eu; /**< '.' */
constexpr FE_Keycode FEK_SLASH                   = 0x0000002fu; /**< '/' */
constexpr FE_Keycode FEK_0                       = 0x00000030u; /**< '0' */
constexpr FE_Keycode FEK_1                       = 0x00000031u; /**< '1' */
constexpr FE_Keycode FEK_2                       = 0x00000032u; /**< '2' */
constexpr FE_Keycode FEK_3                       = 0x00000033u; /**< '3' */
constexpr FE_Keycode FEK_4                       = 0x00000034u; /**< '4' */
constexpr FE_Keycode FEK_5                       = 0x00000035u; /**< '5' */
constexpr FE_Keycode FEK_6                       = 0x00000036u; /**< '6' */
constexpr FE_Keycode FEK_7                       = 0x00000037u; /**< '7' */
constexpr FE_Keycode FEK_8                       = 0x00000038u; /**< '8' */
constexpr FE_Keycode FEK_9                       = 0x00000039u; /**< '9' */
constexpr FE_Keycode FEK_COLON                   = 0x0000003au; /**< ':' */
constexpr FE_Keycode FEK_SEMICOLON               = 0x0000003bu; /**< ';' */
constexpr FE_Keycode FEK_LESS                    = 0x0000003cu; /**< '<' */
constexpr FE_Keycode FEK_EQUALS                  = 0x0000003du; /**< '=' */
constexpr FE_Keycode FEK_GREATER                 = 0x0000003eu; /**< '>' */
constexpr FE_Keycode FEK_QUESTION                = 0x0000003fu; /**< '?' */
constexpr FE_Keycode FEK_AT                      = 0x00000040u; /**< '@' */
constexpr FE_Keycode FEK_LEFTBRACKET             = 0x0000005bu; /**< '[' */
constexpr FE_Keycode FEK_BACKSLASH               = 0x0000005cu; /**< '\\' */
constexpr FE_Keycode FEK_RIGHTBRACKET            = 0x0000005du; /**< ']' */
constexpr FE_Keycode FEK_CARET                   = 0x0000005eu; /**< '^' */
constexpr FE_Keycode FEK_UNDERSCORE              = 0x0000005fu; /**< '_' */
constexpr FE_Keycode FEK_GRAVE                   = 0x00000060u; /**< '`' */
constexpr FE_Keycode FEK_A                       = 0x00000061u; /**< 'a' */
constexpr FE_Keycode FEK_B                       = 0x00000062u; /**< 'b' */
constexpr FE_Keycode FEK_C                       = 0x00000063u; /**< 'c' */
constexpr FE_Keycode FEK_D                       = 0x00000064u; /**< 'd' */
constexpr FE_Keycode FEK_E                       = 0x00000065u; /**< 'e' */
constexpr FE_Keycode FEK_F                       = 0x00000066u; /**< 'f' */
constexpr FE_Keycode FEK_G                       = 0x00000067u; /**< 'g' */
constexpr FE_Keycode FEK_H                       = 0x00000068u; /**< 'h' */
constexpr FE_Keycode FEK_I                       = 0x00000069u; /**< 'i' */
constexpr FE_Keycode FEK_J                       = 0x0000006au; /**< 'j' */
constexpr FE_Keycode FEK_K                       = 0x0000006bu; /**< 'k' */
constexpr FE_Keycode FEK_L                       = 0x0000006cu; /**< 'l' */
constexpr FE_Keycode FEK_M                       = 0x0000006du; /**< 'm' */
constexpr FE_Keycode FEK_N                       = 0x0000006eu; /**< 'n' */
constexpr FE_Keycode FEK_O                       = 0x0000006fu; /**< 'o' */
constexpr FE_Keycode FEK_P                       = 0x00000070u; /**< 'p' */
constexpr FE_Keycode FEK_Q                       = 0x00000071u; /**< 'q' */
constexpr FE_Keycode FEK_R                       = 0x00000072u; /**< 'r' */
constexpr FE_Keycode FEK_S                       = 0x00000073u; /**< 's' */
constexpr FE_Keycode FEK_T                       = 0x00000074u; /**< 't' */
constexpr FE_Keycode FEK_U                       = 0x00000075u; /**< 'u' */
constexpr FE_Keycode FEK_V                       = 0x00000076u; /**< 'v' */
constexpr FE_Keycode FEK_W                       = 0x00000077u; /**< 'w' */
constexpr FE_Keycode FEK_X                       = 0x00000078u; /**< 'x' */
constexpr FE_Keycode FEK_Y                       = 0x00000079u; /**< 'y' */
constexpr FE_Keycode FEK_Z                       = 0x0000007au; /**< 'z' */
constexpr FE_Keycode FEK_LEFTBRACE               = 0x0000007bu; /**< '{' */
constexpr FE_Keycode FEK_PIPE                    = 0x0000007cu; /**< '|' */
constexpr FE_Keycode FEK_RIGHTBRACE              = 0x0000007du; /**< '}' */
constexpr FE_Keycode FEK_TILDE                   = 0x0000007eu; /**< '~' */
constexpr FE_Keycode FEK_DELETE                  = 0x0000007fu; /**< '\x7F' */
constexpr FE_Keycode FEK_PLUSMINUS               = 0x000000b1u; /**< '\xB1' */
constexpr FE_Keycode FEK_CAPSLOCK                = 0x40000039u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CAPSLOCK) */
constexpr FE_Keycode FEK_F1                      = 0x4000003au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F1) */
constexpr FE_Keycode FEK_F2                      = 0x4000003bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F2) */
constexpr FE_Keycode FEK_F3                      = 0x4000003cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F3) */
constexpr FE_Keycode FEK_F4                      = 0x4000003du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F4) */
constexpr FE_Keycode FEK_F5                      = 0x4000003eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F5) */
constexpr FE_Keycode FEK_F6                      = 0x4000003fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F6) */
constexpr FE_Keycode FEK_F7                      = 0x40000040u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F7) */
constexpr FE_Keycode FEK_F8                      = 0x40000041u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F8) */
constexpr FE_Keycode FEK_F9                      = 0x40000042u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F9) */
constexpr FE_Keycode FEK_F10                     = 0x40000043u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F10) */
constexpr FE_Keycode FEK_F11                     = 0x40000044u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F11) */
constexpr FE_Keycode FEK_F12                     = 0x40000045u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F12) */
constexpr FE_Keycode FEK_PRINTSCREEN             = 0x40000046u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_PRINTSCREEN) */
constexpr FE_Keycode FEK_SCROLLLOCK              = 0x40000047u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SCROLLLOCK) */
constexpr FE_Keycode FEK_PAUSE                   = 0x40000048u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_PAUSE) */
constexpr FE_Keycode FEK_INSERT                  = 0x40000049u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_INSERT) */
constexpr FE_Keycode FEK_HOME                    = 0x4000004au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_HOME) */
constexpr FE_Keycode FEK_PAGEUP                  = 0x4000004bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_PAGEUP) */
constexpr FE_Keycode FEK_END                     = 0x4000004du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_END) */
constexpr FE_Keycode FEK_PAGEDOWN                = 0x4000004eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_PAGEDOWN) */
constexpr FE_Keycode FEK_RIGHT                   = 0x4000004fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_RIGHT) */
constexpr FE_Keycode FEK_LEFT                    = 0x40000050u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_LEFT) */
constexpr FE_Keycode FEK_DOWN                    = 0x40000051u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_DOWN) */
constexpr FE_Keycode FEK_UP                      = 0x40000052u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_UP) */
constexpr FE_Keycode FEK_NUMLOCKCLEAR            = 0x40000053u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_NUMLOCKCLEAR) */
constexpr FE_Keycode FEK_KP_DIVIDE               = 0x40000054u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_DIVIDE) */
constexpr FE_Keycode FEK_KP_MULTIPLY             = 0x40000055u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MULTIPLY) */
constexpr FE_Keycode FEK_KP_MINUS                = 0x40000056u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MINUS) */
constexpr FE_Keycode FEK_KP_PLUS                 = 0x40000057u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_PLUS) */
constexpr FE_Keycode FEK_KP_ENTER                = 0x40000058u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_ENTER) */
constexpr FE_Keycode FEK_KP_1                    = 0x40000059u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_1) */
constexpr FE_Keycode FEK_KP_2                    = 0x4000005au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_2) */
constexpr FE_Keycode FEK_KP_3                    = 0x4000005bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_3) */
constexpr FE_Keycode FEK_KP_4                    = 0x4000005cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_4) */
constexpr FE_Keycode FEK_KP_5                    = 0x4000005du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_5) */
constexpr FE_Keycode FEK_KP_6                    = 0x4000005eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_6) */
constexpr FE_Keycode FEK_KP_7                    = 0x4000005fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_7) */
constexpr FE_Keycode FEK_KP_8                    = 0x40000060u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_8) */
constexpr FE_Keycode FEK_KP_9                    = 0x40000061u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_9) */
constexpr FE_Keycode FEK_KP_0                    = 0x40000062u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_0) */
constexpr FE_Keycode FEK_KP_PERIOD               = 0x40000063u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_PERIOD) */
constexpr FE_Keycode FEK_APPLICATION             = 0x40000065u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_APPLICATION) */
constexpr FE_Keycode FEK_POWER                   = 0x40000066u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_POWER) */
constexpr FE_Keycode FEK_KP_EQUALS               = 0x40000067u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_EQUALS) */
constexpr FE_Keycode FEK_F13                     = 0x40000068u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F13) */
constexpr FE_Keycode FEK_F14                     = 0x40000069u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F14) */
constexpr FE_Keycode FEK_F15                     = 0x4000006au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F15) */
constexpr FE_Keycode FEK_F16                     = 0x4000006bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F16) */
constexpr FE_Keycode FEK_F17                     = 0x4000006cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F17) */
constexpr FE_Keycode FEK_F18                     = 0x4000006du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F18) */
constexpr FE_Keycode FEK_F19                     = 0x4000006eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F19) */
constexpr FE_Keycode FEK_F20                     = 0x4000006fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F20) */
constexpr FE_Keycode FEK_F21                     = 0x40000070u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F21) */
constexpr FE_Keycode FEK_F22                     = 0x40000071u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F22) */
constexpr FE_Keycode FEK_F23                     = 0x40000072u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F23) */
constexpr FE_Keycode FEK_F24                     = 0x40000073u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_F24) */
constexpr FE_Keycode FEK_EXECUTE                 = 0x40000074u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_EXECUTE) */
constexpr FE_Keycode FEK_HELP                    = 0x40000075u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_HELP) */
constexpr FE_Keycode FEK_MENU                    = 0x40000076u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MENU) */
constexpr FE_Keycode FEK_SELECT                  = 0x40000077u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SELECT) */
constexpr FE_Keycode FEK_STOP                    = 0x40000078u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_STOP) */
constexpr FE_Keycode FEK_AGAIN                   = 0x40000079u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AGAIN) */
constexpr FE_Keycode FEK_UNDO                    = 0x4000007au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_UNDO) */
constexpr FE_Keycode FEK_CUT                     = 0x4000007bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CUT) */
constexpr FE_Keycode FEK_COPY                    = 0x4000007cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_COPY) */
constexpr FE_Keycode FEK_PASTE                   = 0x4000007du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_PASTE) */
constexpr FE_Keycode FEK_FIND                    = 0x4000007eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_FIND) */
constexpr FE_Keycode FEK_MUTE                    = 0x4000007fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MUTE) */
constexpr FE_Keycode FEK_VOLUMEUP                = 0x40000080u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_VOLUMEUP) */
constexpr FE_Keycode FEK_VOLUMEDOWN              = 0x40000081u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_VOLUMEDOWN) */
constexpr FE_Keycode FEK_KP_COMMA                = 0x40000085u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_COMMA) */
constexpr FE_Keycode FEK_KP_EQUALSAS400          = 0x40000086u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_EQUALSAS400) */
constexpr FE_Keycode FEK_ALTERASE                = 0x40000099u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_ALTERASE) */
constexpr FE_Keycode FEK_SYSREQ                  = 0x4000009au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SYSREQ) */
constexpr FE_Keycode FEK_CANCEL                  = 0x4000009bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CANCEL) */
constexpr FE_Keycode FEK_CLEAR                   = 0x4000009cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CLEAR) */
constexpr FE_Keycode FEK_PRIOR                   = 0x4000009du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_PRIOR) */
constexpr FE_Keycode FEK_RETURN2                 = 0x4000009eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_RETURN2) */
constexpr FE_Keycode FEK_SEPARATOR               = 0x4000009fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SEPARATOR) */
constexpr FE_Keycode FEK_OUT                     = 0x400000a0u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_OUT) */
constexpr FE_Keycode FEK_OPER                    = 0x400000a1u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_OPER) */
constexpr FE_Keycode FEK_CLEARAGAIN              = 0x400000a2u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CLEARAGAIN) */
constexpr FE_Keycode FEK_CRSEL                   = 0x400000a3u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CRSEL) */
constexpr FE_Keycode FEK_EXSEL                   = 0x400000a4u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_EXSEL) */
constexpr FE_Keycode FEK_KP_00                   = 0x400000b0u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_00) */
constexpr FE_Keycode FEK_KP_000                  = 0x400000b1u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_000) */
constexpr FE_Keycode FEK_THOUSANDSSEPARATOR      = 0x400000b2u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_THOUSANDSSEPARATOR) */
constexpr FE_Keycode FEK_DECIMALSEPARATOR        = 0x400000b3u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_DECIMALSEPARATOR) */
constexpr FE_Keycode FEK_CURRENCYUNIT            = 0x400000b4u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CURRENCYUNIT) */
constexpr FE_Keycode FEK_CURRENCYSUBUNIT         = 0x400000b5u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CURRENCYSUBUNIT) */
constexpr FE_Keycode FEK_KP_LEFTPAREN            = 0x400000b6u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_LEFTPAREN) */
constexpr FE_Keycode FEK_KP_RIGHTPAREN           = 0x400000b7u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_RIGHTPAREN) */
constexpr FE_Keycode FEK_KP_LEFTBRACE            = 0x400000b8u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_LEFTBRACE) */
constexpr FE_Keycode FEK_KP_RIGHTBRACE           = 0x400000b9u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_RIGHTBRACE) */
constexpr FE_Keycode FEK_KP_TAB                  = 0x400000bau; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_TAB) */
constexpr FE_Keycode FEK_KP_BACKSPACE            = 0x400000bbu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_BACKSPACE) */
constexpr FE_Keycode FEK_KP_A                    = 0x400000bcu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_A) */
constexpr FE_Keycode FEK_KP_B                    = 0x400000bdu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_B) */
constexpr FE_Keycode FEK_KP_C                    = 0x400000beu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_C) */
constexpr FE_Keycode FEK_KP_D                    = 0x400000bfu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_D) */
constexpr FE_Keycode FEK_KP_E                    = 0x400000c0u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_E) */
constexpr FE_Keycode FEK_KP_F                    = 0x400000c1u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_F) */
constexpr FE_Keycode FEK_KP_XOR                  = 0x400000c2u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_XOR) */
constexpr FE_Keycode FEK_KP_POWER                = 0x400000c3u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_POWER) */
constexpr FE_Keycode FEK_KP_PERCENT              = 0x400000c4u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_PERCENT) */
constexpr FE_Keycode FEK_KP_LESS                 = 0x400000c5u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_LESS) */
constexpr FE_Keycode FEK_KP_GREATER              = 0x400000c6u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_GREATER) */
constexpr FE_Keycode FEK_KP_AMPERSAND            = 0x400000c7u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_AMPERSAND) */
constexpr FE_Keycode FEK_KP_DBLAMPERSAND         = 0x400000c8u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_DBLAMPERSAND) */
constexpr FE_Keycode FEK_KP_VERTICALBAR          = 0x400000c9u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_VERTICALBAR) */
constexpr FE_Keycode FEK_KP_DBLVERTICALBAR       = 0x400000cau; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_DBLVERTICALBAR) */
constexpr FE_Keycode FEK_KP_COLON                = 0x400000cbu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_COLON) */
constexpr FE_Keycode FEK_KP_HASH                 = 0x400000ccu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_HASH) */
constexpr FE_Keycode FEK_KP_SPACE                = 0x400000cdu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_SPACE) */
constexpr FE_Keycode FEK_KP_AT                   = 0x400000ceu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_AT) */
constexpr FE_Keycode FEK_KP_EXCLAM               = 0x400000cfu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_EXCLAM) */
constexpr FE_Keycode FEK_KP_MEMSTORE             = 0x400000d0u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMSTORE) */
constexpr FE_Keycode FEK_KP_MEMRECALL            = 0x400000d1u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMRECALL) */
constexpr FE_Keycode FEK_KP_MEMCLEAR             = 0x400000d2u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMCLEAR) */
constexpr FE_Keycode FEK_KP_MEMADD               = 0x400000d3u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMADD) */
constexpr FE_Keycode FEK_KP_MEMSUBTRACT          = 0x400000d4u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMSUBTRACT) */
constexpr FE_Keycode FEK_KP_MEMMULTIPLY          = 0x400000d5u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMMULTIPLY) */
constexpr FE_Keycode FEK_KP_MEMDIVIDE            = 0x400000d6u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_MEMDIVIDE) */
constexpr FE_Keycode FEK_KP_PLUSMINUS            = 0x400000d7u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_PLUSMINUS) */
constexpr FE_Keycode FEK_KP_CLEAR                = 0x400000d8u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_CLEAR) */
constexpr FE_Keycode FEK_KP_CLEARENTRY           = 0x400000d9u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_CLEARENTRY) */
constexpr FE_Keycode FEK_KP_BINARY               = 0x400000dau; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_BINARY) */
constexpr FE_Keycode FEK_KP_OCTAL                = 0x400000dbu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_OCTAL) */
constexpr FE_Keycode FEK_KP_DECIMAL              = 0x400000dcu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_DECIMAL) */
constexpr FE_Keycode FEK_KP_HEXADECIMAL          = 0x400000ddu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_KP_HEXADECIMAL) */
constexpr FE_Keycode FEK_LCTRL                   = 0x400000e0u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_LCTRL) */
constexpr FE_Keycode FEK_LSHIFT                  = 0x400000e1u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_LSHIFT) */
constexpr FE_Keycode FEK_LALT                    = 0x400000e2u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_LALT) */
constexpr FE_Keycode FEK_LGUI                    = 0x400000e3u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_LGUI) */
constexpr FE_Keycode FEK_RCTRL                   = 0x400000e4u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_RCTRL) */
constexpr FE_Keycode FEK_RSHIFT                  = 0x400000e5u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_RSHIFT) */
constexpr FE_Keycode FEK_RALT                    = 0x400000e6u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_RALT) */
constexpr FE_Keycode FEK_RGUI                    = 0x400000e7u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_RGUI) */
constexpr FE_Keycode FEK_MODE                    = 0x40000101u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MODE) */
constexpr FE_Keycode FEK_SLEEP                   = 0x40000102u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SLEEP) */
constexpr FE_Keycode FEK_WAKE                    = 0x40000103u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_WAKE) */
constexpr FE_Keycode FEK_CHANNEL_INCREMENT       = 0x40000104u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CHANNEL_INCREMENT) */
constexpr FE_Keycode FEK_CHANNEL_DECREMENT       = 0x40000105u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CHANNEL_DECREMENT) */
constexpr FE_Keycode FEK_MEDIA_PLAY              = 0x40000106u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_PLAY) */
constexpr FE_Keycode FEK_MEDIA_PAUSE             = 0x40000107u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_PAUSE) */
constexpr FE_Keycode FEK_MEDIA_RECORD            = 0x40000108u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_RECORD) */
constexpr FE_Keycode FEK_MEDIA_FAST_FORWARD      = 0x40000109u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_FAST_FORWARD) */
constexpr FE_Keycode FEK_MEDIA_REWIND            = 0x4000010au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_REWIND) */
constexpr FE_Keycode FEK_MEDIA_NEXT_TRACK        = 0x4000010bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_NEXT_TRACK) */
constexpr FE_Keycode FEK_MEDIA_PREVIOUS_TRACK    = 0x4000010cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_PREVIOUS_TRACK) */		
constexpr FE_Keycode FEK_MEDIA_STOP              = 0x4000010du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_STOP) */
constexpr FE_Keycode FEK_MEDIA_EJECT             = 0x4000010eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_EJECT) */
constexpr FE_Keycode FEK_MEDIA_PLAY_PAUSE        = 0x4000010fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_PLAY_PAUSE) */
constexpr FE_Keycode FEK_MEDIA_SELECT            = 0x40000110u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_MEDIA_SELECT) */
constexpr FE_Keycode FEK_AC_NEW                  = 0x40000111u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_NEW) */
constexpr FE_Keycode FEK_AC_OPEN                 = 0x40000112u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_OPEN) */
constexpr FE_Keycode FEK_AC_CLOSE                = 0x40000113u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_CLOSE) */
constexpr FE_Keycode FEK_AC_EXIT                 = 0x40000114u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_EXIT) */
constexpr FE_Keycode FEK_AC_SAVE                 = 0x40000115u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_SAVE) */
constexpr FE_Keycode FEK_AC_PRINT                = 0x40000116u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_PRINT) */
constexpr FE_Keycode FEK_AC_PROPERTIES           = 0x40000117u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_PROPERTIES) */
constexpr FE_Keycode FEK_AC_SEARCH               = 0x40000118u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_SEARCH) */
constexpr FE_Keycode FEK_AC_HOME                 = 0x40000119u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_HOME) */
constexpr FE_Keycode FEK_AC_BACK                 = 0x4000011au; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_BACK) */
constexpr FE_Keycode FEK_AC_FORWARD              = 0x4000011bu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_FORWARD) */
constexpr FE_Keycode FEK_AC_STOP                 = 0x4000011cu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_STOP) */
constexpr FE_Keycode FEK_AC_REFRESH              = 0x4000011du; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_REFRESH) */
constexpr FE_Keycode FEK_AC_BOOKMARKS            = 0x4000011eu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_AC_BOOKMARKS) */
constexpr FE_Keycode FEK_SOFTLEFT                = 0x4000011fu; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SOFTLEFT) */
constexpr FE_Keycode FEK_SOFTRIGHT               = 0x40000120u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_SOFTRIGHT) */
constexpr FE_Keycode FEK_CALL                    = 0x40000121u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_CALL) */
constexpr FE_Keycode FEK_ENDCALL                 = 0x40000122u; /**< FE_SCANCODE_TO_KEYCODE(FE_SCANCODE_ENDCALL) */
constexpr FE_Keycode FEK_LEFT_TAB                = 0x20000001u; /**< Extended key Left Tab */
constexpr FE_Keycode FEK_LEVEL5_SHIFT            = 0x20000002u; /**< Extended key Level 5 Shift */
constexpr FE_Keycode FEK_MULTI_KEY_COMPOSE       = 0x20000003u; /**< Extended key Multi-key Compose */
constexpr FE_Keycode FEK_LMETA                   = 0x20000004u; /**< Extended key Left Meta */
constexpr FE_Keycode FEK_RMETA                   = 0x20000005u; /**< Extended key Right Meta */
constexpr FE_Keycode FEK_LHYPER                  = 0x20000006u; /**< Extended key Left Hyper */
constexpr FE_Keycode FEK_RHYPER                  = 0x20000007u; /**< Extended key Right Hyper */

typedef uint16_t FE_Keymod;

constexpr FE_Keymod FE_KMOD_NONE    = 0x0000u; /**< no modifier is applicable. */
constexpr FE_Keymod FE_KMOD_LSHIFT  = 0x0001u; /**< the left Shift key is down. */
constexpr FE_Keymod FE_KMOD_RSHIFT  = 0x0002u; /**< the right Shift key is down. */
constexpr FE_Keymod FE_KMOD_LEVEL5  = 0x0004u; /**< the Level 5 Shift key is down. */
constexpr FE_Keymod FE_KMOD_LCTRL   = 0x0040u; /**< the left Ctrl (Control) key is down. */
constexpr FE_Keymod FE_KMOD_RCTRL   = 0x0080u; /**< the right Ctrl (Control) key is down. */
constexpr FE_Keymod FE_KMOD_LALT    = 0x0100u; /**< the left Alt key is down. */
constexpr FE_Keymod FE_KMOD_RALT    = 0x0200u; /**< the right Alt key is down. */
constexpr FE_Keymod FE_KMOD_LGUI    = 0x0400u; /**< the left GUI key (often the Windows key) is down. */
constexpr FE_Keymod FE_KMOD_RGUI    = 0x0800u; /**< the right GUI key (often the Windows key) is down. */
constexpr FE_Keymod FE_KMOD_NUM     = 0x1000u; /**< the Num Lock key (may be located on an extended keypad) is down. */
constexpr FE_Keymod FE_KMOD_CAPS    = 0x2000u; /**< the Caps Lock key is down. */
constexpr FE_Keymod FE_KMOD_MODE    = 0x4000u; /**< the !AltGr key is down. */
constexpr FE_Keymod FE_KMOD_SCROLL  = 0x8000u; /**< the Scroll Lock key is down. */
constexpr FE_Keymod FE_KMOD_CTRL	= (SDL_KMOD_LCTRL | SDL_KMOD_RCTRL);   /**< Any Ctrl key is down. */
constexpr FE_Keymod FE_KMOD_SHIFT	= (SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT); /**< Any Shift key is down. */
constexpr FE_Keymod FE_KMOD_ALT		= (SDL_KMOD_LALT | SDL_KMOD_RALT);    /**< Any Alt key is down. */
constexpr FE_Keymod FE_KMOD_GUI		= (SDL_KMOD_LGUI | SDL_KMOD_RGUI);     /**< Any GUI key is down. */

